name: myenv
channels:
  - conda-forge
dependencies:
  - python=3.9.19  # 假设您使用Python 3.8
  - numpy=1.26.4
  - pandas=2.2.1
  - matplotlib=3.8.4  # 需要从您的环境确认版本
  - geopandas=0.14.3
  - folium=0.16.0
  - ipywidgets=8.1.2
  - notebook  # Jupyter Notebook
  - pip:
    - plotly  # 如果您还需要其他通过pip安装的包
